In [4]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os

for root, dirs, files in os.walk("/kaggle/input"):
    for f in files:
        if f.endswith(".csv"):
            print(os.path.join(root, f))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/sia-predicting-short-form-video-popularity/X_test.csv
/kaggle/input/competitions/sia-predicting-short-form-video-popularity/y_train.csv
/kaggle/input/competitions/sia-predicting-short-form-video-popularity/X_train.csv

In [ ]:
x_train_path = "/sia-predicting-short-form-video-popularity/X_train.csv"

with open(x_train_path, "r", encoding="utf-8", errors="replace") as f:
    for i in range(15):
        print(f"{i+1:02d}:", f.readline().rstrip("\n"))

01: id;album;artist;artists;aspect_ratio;channel;description;video_duration;format;release_year;track;uploader;filepath;download_timing;uploader_short;vid;uid
02: 7602656035161050390;;Urhov Bogdan;['Urhov Bogdan'];0.56;Davos Klosters;you dream you 🥹 #davosklosters #skiing #mountains #swiss #davos ;13;1080x1920;2026;оригинальный звук;davosklosters;downloads/USER_davosklosters/VIDEO_7602656035161050390.mp4;2026-02-12 09:29:25;davos;VIDEO_7602656035161050390;USER_davosklosters
03: 7590718903144287510;;LykTraffx;['LykTraffx'];0.56;Davos Klosters;already missing this again 🥹 #spenglercup #davos #hockey #hcd #core ;12;1080x1920;2026;оригинальный звук;davosklosters;downloads/USER_davosklosters/VIDEO_7590718903144287510.mp4;2026-02-12 09:29:25;davos;VIDEO_7590718903144287510;USER_davosklosters
04: 7571821778746592534;;ALTÉGO;['ALTÉGO'];0.56;Davos Klosters;how??!!!🥹🥹 #davosklosters #skiing #ski #seasonopening #davos ;13;1080x1920;2025;THE FATE OF OPHELIA X MIDNIGHT CITY;davosklosters;downloads/USER_davosklosters/VIDEO_7571821778746592534.mp4;2026-02-12 09:29:25;davos;VIDEO_7571821778746592534;USER_davosklosters
05: 7569927329154190614;;Raye;['Raye'];0.56;Davos Klosters;We're back on snow!🥹🎿 #davosklosters #seasonopening #skiing #davos ;7;1080x1920;2025;original sound;davosklosters;downloads/USER_davosklosters/VIDEO_7569927329154190614.mp4;2026-02-12 09:29:25;davos;VIDEO_7569927329154190614;USER_davosklosters
06: 7566270741134462230;;músicas e traduções;['músicas e traduções'];0.56;Davos Klosters;Somebody send help, pls. 🥶 #davos #firstsnow #interval #run #snow ;8;1080x1920;2025;som original;davosklosters;downloads/USER_davosklosters/VIDEO_7566270741134462230.mp4;2026-02-12 09:29:25;davos;VIDEO_7566270741134462230;USER_davosklosters
07: 7536170254989315350;;Michael Buckley;['Michael Buckley'];0.56;Davos Klosters;bald bald 🥹🫰🏽🎿 #davosklosters #sportsunlimited #ski #skiseasonn #davos #winter;12;1080x1920;2025;This is your sign to fly;davosklosters;downloads/USER_davosklosters/VIDEO_7536170254989315350.mp4;2026-02-12 09:29:25;davos;VIDEO_7536170254989315350;USER_davosklosters
08: 7520640970199698710;;E🩶;['E🩶'];0.56;Davos Klosters;Holy fckn airball 😎✌🏽  #davosklosters #holyfcknairball #trend #fyp #hiking #mountains ;10;576x1024;2025;ECE Marketing Airball;davosklosters;downloads/USER_davosklosters/VIDEO_7520640970199698710.mp4;2026-02-12 09:29:25;davos;VIDEO_7520640970199698710;USER_davosklosters
09: 7496799936558796054;;user43952297847;['user43952297847'];0.56;Davos Klosters;Saisonende? Was?!🥹 #davosklosters #seasonend #skiing #winter #springskiing ;14;1080x1920;2025;Never Let Me Go;davosklosters;downloads/USER_davosklosters/VIDEO_7496799936558796054.mp4;2026-02-12 09:29:25;davos;VIDEO_7496799936558796054;USER_davosklosters
10: 7487960173529582870;;ZOMBIE;['ZOMBIE'];0.56;Davos Klosters;Willkommen zurück im Winter!🥹🎿 Wer hat auch noch nicht genug?🫶🏽 #davosklosters #snow #winter #freshsnow #wintervssummer ;8;1080x1920;2025;headlock x jinx from arcane;davosklosters;downloads/USER_davosklosters/VIDEO_7487960173529582870.mp4;2026-02-12 09:29:25;davos;VIDEO_7487960173529582870;USER_davosklosters
11: 7478712216724802838;;Stan :);['Stan :)'];0.56;Davos Klosters;März, wir lieben dich!🥹🫶🏽 #davosklosters #skiing #thisfeeling #ski #davos #swiss #mountains ;14;1080x1920;2025;original sound;davosklosters;downloads/USER_davosklosters/VIDEO_7478712216724802838.mp4;2026-02-12 09:29:25;davos;VIDEO_7478712216724802838;USER_davosklosters
12: 7470850262840691990;;Julian Witting;['Julian Witting'];0.56;Davos Klosters;Nichts Besseres, oder?🥹🎿 #davosklosters #skiing #whatskiingfeelslike #davos #winter #fyp #TikTokTrends #skitok ;8;1080x1920;2025;Originalton;davosklosters;downloads/USER_davosklosters/VIDEO_7470850262840691990.mp4;2026-02-12 09:29:25;davos;VIDEO_7470850262840691990;USER_davosklosters
13: 7424512450856357153;;<3;['<3'];0.56;Davos Klosters;bald geht's los 🥹🎿 #davosklosters #skitok #graubünden #winter #snow #swiss #davos ;8;1080x1920;2024;original sound;davosklosters;downloads/USER_davosklosters/VIDEO_7424512450856357153.mp4;2026-02-12 09:29:25;davos;VIDEO_7424512450856357153;USER_davosklosters
14: 7416286728513735968;;vih_a.r;['vih_a.r'];0.56;Davos Klosters;❤️‍🩹 Wem geht‘s auch so? #davosklosters #problemstrend #sunrise #swissmountains #graubünden #jöriseen ;7;1080x1920;2024;som original;davosklosters;downloads/USER_davosklosters/VIDEO_7416286728513735968.mp4;2026-02-12 09:29:25;davos;VIDEO_7416286728513735968;USER_davosklosters
15: 7374727208394411297;;Bigteddy_73;['Bigteddy_73'];0.56;Davos Klosters;Sommer, wo bleibst du?🥲☔️ #davosklosters #sportsunlimited #weareback #trends #mountainlife #swisstok #switzerland #mountains #summer #davos #graubünden ;8;720x1280;2024;original sound;davosklosters;downloads/USER_davosklosters/VIDEO_7374727208394411297.mp4;2026-02-12 09:29:25;davos;VIDEO_7374727208394411297;USER_davosklosters

In [2]:
import pandas as pd

x_train_path = "./sia-predicting-short-form-video-popularity/X_train.csv"
X_train = pd.read_csv(x_train_path, sep=";")

In [3]:
X_train.head()

,id,album,artist,artists,aspect_ratio,channel,description,video_duration,format,release_year,track,uploader,filepath,download_timing,uploader_short,vid,uid
0,7602656035161050390,NaN,Urhov Bogdan,['Urhov Bogdan'],0.56,Davos Klosters,you dream you 🥹 #davosklosters #skiing #mounta...,13,1080x1920,2026,оригинальный звук,davosklosters,downloads/USER_davosklosters/VIDEO_76026560351...,2026-02-12 09:29:25,davos,VIDEO_7602656035161050390,USER_davosklosters
1,7590718903144287510,NaN,LykTraffx,['LykTraffx'],0.56,Davos Klosters,already missing this again 🥹 #spenglercup #dav...,12,1080x1920,2026,оригинальный звук,davosklosters,downloads/USER_davosklosters/VIDEO_75907189031...,2026-02-12 09:29:25,davos,VIDEO_7590718903144287510,USER_davosklosters
2,7571821778746592534,NaN,ALTÉGO,['ALTÉGO'],0.56,Davos Klosters,how??!!!🥹🥹 #davosklosters #skiing #ski #season...,13,1080x1920,2025,THE FATE OF OPHELIA X MIDNIGHT CITY,davosklosters,downloads/USER_davosklosters/VIDEO_75718217787...,2026-02-12 09:29:25,davos,VIDEO_7571821778746592534,USER_davosklosters
3,7569927329154190614,NaN,Raye,['Raye'],0.56,Davos Klosters,We're back on snow!🥹🎿 #davosklosters #seasonop...,7,1080x1920,2025,original sound,davosklosters,downloads/USER_davosklosters/VIDEO_75699273291...,2026-02-12 09:29:25,davos,VIDEO_7569927329154190614,USER_davosklosters
4,7566270741134462230,NaN,músicas e traduções,['músicas e traduções'],0.56,Davos Klosters,"Somebody send help, pls. 🥶 #davos #firstsnow #...",8,1080x1920,2025,som original,davosklosters,downloads/USER_davosklosters/VIDEO_75662707411...,2026-02-12 09:29:25,davos,VIDEO_7566270741134462230,USER_davosklosters

In [4]:
X_train.describe()

                 id  aspect_ratio  video_duration  release_year
count  1.348000e+03   1348.000000     1348.000000   1348.000000
mean   7.285740e+18      0.566639       10.182493   2023.299703
std    1.925176e+17      0.069361        2.477682      1.418124
min    6.739805e+18      0.460000        6.000000   2019.000000
25%    7.157497e+18      0.560000        8.000000   2022.000000
50%    7.296286e+18      0.560000       10.000000   2023.000000
75%    7.452477e+18      0.560000       12.000000   2024.000000
max    7.606361e+18      1.780000       14.000000   2026.000000

In [5]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1348 entries, 0 to 1347
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1348 non-null   int64
 1   album            375 non-null    object
 2   artist           1317 non-null   object
 3   artists          1317 non-null   object
 4   aspect_ratio     1348 non-null   float64
 5   channel          1348 non-null   object
 6   description      1343 non-null   object
 7   video_duration   1348 non-null   int64
 8   format           1348 non-null   object
 9   release_year     1348 non-null   int64
 10  track            1322 non-null   object
 11  uploader         1348 non-null   object
 12  filepath         1348 non-null   object
 13  download_timing  1348 non-null   object
 14  uploader_short   1348 non-null   object
 15  vid              1348 non-null   object
 16  uid              1348 non-null   object
dtypes: float64(1), int64(3), object(13)
memory usage: 179.2+ KB

In [6]:
y_train_path = "./sia-predicting-short-form-video-popularity/y_train.csv"
y_train = pd.read_csv(y_train_path, sep=";")

In [7]:
y_train.head()

                    ID  popularity
0  7602656035161050390    8.603777
1  7590718903144287510    8.537734
2  7571821778746592534   11.208495
3  7569927329154190614   11.982352
4  7566270741134462230    8.678487

In [8]:
y_train.describe()

                 ID   popularity
count  1.348000e+03  1348.000000
mean   7.285740e+18     7.804249
std    1.925176e+17     1.686488
min    6.739805e+18     3.487629
25%    7.157497e+18     6.724373
50%    7.296286e+18     7.497118
75%    7.452477e+18     8.772238
max    7.606361e+18    14.407981

In [9]:
df = X_train.merge(y_train, left_on="id", right_on="ID", how="inner")

In [10]:
# df = X_train.merge(y_train, left_on="id", right_on="ID", how="inner")

target_col = "popularity"  # adapte si ta cible a un autre nom

num_df = df.select_dtypes(include="number").drop(columns=["id", "ID"], errors="ignore")

corr_matrix = num_df.corr(numeric_only=True)
corr_with_target = corr_matrix[target_col].sort_values(ascending=False)

corr_matrix, corr_with_target

(                aspect_ratio  video_duration  release_year  popularity
 aspect_ratio        1.000000        0.037742      0.000284   -0.011222
 video_duration      0.037742        1.000000     -0.031635   -0.037191
 release_year        0.000284       -0.031635      1.000000    0.066608
 popularity         -0.011222       -0.037191      0.066608    1.000000,
 popularity        1.000000
 release_year      0.066608
 aspect_ratio     -0.011222
 video_duration   -0.037191
 Name: popularity, dtype: float64)

In [11]:
corr_matrix

                aspect_ratio  video_duration  release_year  popularity
aspect_ratio        1.000000        0.037742      0.000284   -0.011222
video_duration      0.037742        1.000000     -0.031635   -0.037191
release_year        0.000284       -0.031635      1.000000    0.066608
popularity         -0.011222       -0.037191      0.066608    1.000000

In [12]:
corr_with_target

popularity        1.000000
release_year      0.066608
aspect_ratio     -0.011222
video_duration   -0.037191
Name: popularity, dtype: float64